# configs/default.yaml


doi_to_md:
  doi: doi:10.17026/SS/R5XWCC
  #doi: doi:10.17026/SS/8TI9GR
  #doi: doi:10.17026/SS/VWPJD5 
  #doi: doi:10.17026/SS/JW3R0M
  base_url: https://ssh.datastations.nl/api/datasets/export?exporter=OAI_ORE&persistentId=

generate_keywords:
  api_key: MY_API_KEY
  model: "openai/gpt-oss-20b:groq"
  api_url: https://router.huggingface.co/v1/chat/completions

match_keywords_to_terms:
  cosine_threshold: 0.8
  matching_method: "top_n" # options: "closest" or "top_n"

prompts: 
  generate_keywords: |
    Instruction: Select up to 10 terms from the Getty AAT (https://vocab.getty.edu/aat/) that summarize the contents of the dataset description below. Only choose terms that are present in the AAT.
    Format: Please format your output as follows: 'name_term_1, name_term_2, name_term_3, name_term_4, name_term_5'
    Dataset description: {metadata}

format_output: 
  base_path : "data/output/{doi}_{method}_{cosine}.csv"  
  output_mode: compact # options: "experimental" and "compact"


embeddings:
  method: SBERT
  sbert_model: "multi-qa-MiniLM-L6-cos-v1"
  lookup_dict_path: "data/aatc_sbert_lookup.pkl"
  # method: fasttext
  # model_path: "models/cc.en.300.bin"
  # lookup_dict_path: "../../data/aatc_fasttext_lookup.pkl"